name: ci

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 16.4.2

      - uses: actions/cache@c1a5de879eb890d062a85ee0252d6036480b1fe2 # v3.2.1
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - run: npm install

      - run: npm run lint

      - run: npm test
      - run: npm run demo
