name: ci

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.3.1
        with:
          node-version: 16.4.2

      - uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - run: npm install

      - run: npm run lint

      - run: npm test
      - run: npm run demo
