name: ci

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3.1.1
        with:
          node-version: 16.4.2

      - uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09 # tag=v3.0.2
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - run: npm install

      - run: npm run lint

      - run: npm test
      - run: npm run demo
